### PR TITLE
Add support of big-bird in config for ORTOptimizer 

### PR DESCRIPTION
**Pull request by lewisbails**
# What does this PR do?
This small PR adds config for big-bird based models to be used in ORTOptimizer.

### CODE REVIEW

**Comment by JingyaHuang** [comment]
Pinging @michaelbenayoun , after the refactoring what would be the check workflow? Shall we add every new model to hf-internal-testing?

**Comment by JingyaHuang** [comment]
Hi @lewisbails , can you also add a test in `tests/onnxruntime/test_optimization.py`, with [`hf-internal-testing/tiny-random-big_bird`](https://huggingface.co/hf-internal-testing/tiny-random-big_bird/tree/main)?

**Comment by lewisbails** [comment]
Okay, @JingyaHuang, I added the tiny-random-big_bird test.
FWIW, I am not convinced that onnxruntime can properly optimize for long input models like BigBird. I have seen poor results trying it directly through the onnxruntime library.

**Comment by JingyaHuang** [comment]
> Okay, @JingyaHuang, I added the tiny-random-big_bird test. FWIW, I am not convinced that onnxruntime can properly optimize for long input models like BigBird. I have seen poor results trying it directly through the onnxruntime library.

Hi @lewisbails, thanks for adding the test. Your comment on the performance sounds very interesting, could you share with us more details about your experiment?

**Review by JingyaHuang — APPROVED** [review]
LGTM!

**Comment by lewisbails** [comment]
Here are a the results of my NER experiment. I used Optimum for creating the ONNX model, and the onnxruntime library for optimisation and quantisation. The original model is a BigBirdForTokenClassification. I tried various optimisation and quantisation configurations, but couldn't find anything that beat using the pytorch model on GPU or CPU in terms of performance, and the quantised models had significantly worse statistical performance.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/ljbails/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/ljbails/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



period (sec/doc) | onnx-format | device | accelerator | inference api | disable_online_opt | serialiser api | optimiser api | quantiser api | quantise_type | quantise_weight_type | quantise_reduce_range | quantise_per_channel
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
0.41 | FALSE | cuda:0 |   | transformers |   |   |   |   |   |   |   |  
2.15 | FALSE | cpu |   | transformers |   |   |   |   |   |   |   |  
3.43 | TRUE | cpu | onnxruntime | optimum | FALSE | optimum | onnxruntime | onnxruntime | dynamic | int8 | FALSE | FALSE
3.46 | TRUE | cpu | onnxruntime | onnxruntime | TRUE | optimum | onnxruntime | onnxruntime | dynamic | int8 | FALSE | FALSE
3.48 | TRUE | cpu | onnxruntime | optimum | FALSE | optimum |   | onnxruntime | dynamic | uint8 | FALSE | FALSE
3.53 | TRUE | cpu | onnxruntime | optimum | FALSE | optimum |   | onnxruntime | dynamic | int8 | FALSE | FALSE
3.95 | TRUE | cpu | onnxruntime | onnxruntime | TRUE | optimum |   | onnxruntime | dynamic | int8 | FALSE | FALSE
3.97 | TRUE | cpu | onnxruntime | onnxruntime | TRUE | optimum |   | onnxruntime | dynamic | uint8 | FALSE | FALSE
4.05 | TRUE | cpu | onnxruntime | optimum | FALSE | optimum | onnxruntime |   |   |   |   |  
4.06 | TRUE | cpu | onnxruntime | onnxruntime | TRUE | optimum | onnxruntime |   |   |   |   |  
4.42 | TRUE | cpu | onnxruntime | optimum | FALSE | optimum |   |   |   |   |   |  
4.47 | TRUE | cpu | onnxruntime | onnxruntime | TRUE | optimum |   |   |   |   |   |  
4.57 | TRUE | cpu | onnxruntime | optimum | FALSE | optimum | onnxruntime | onnxruntime | dynamic | uint8 | FALSE | FALSE
4.65 | TRUE | cpu | onnxruntime | onnxruntime | TRUE | optimum | onnxruntime | onnxruntime | dynamic | uint8 | TRUE | TRUE
4.85 | TRUE | cpu | onnxruntime | onnxruntime | TRUE | optimum | onnxruntime | onnxruntime | dynamic | uint8 | FALSE | FALSE
5.15 | TRUE | cpu | onnxruntime | onnxruntime | TRUE | optimum |   | onnxruntime | dynamic | uint8 | TRUE | TRUE



</body>

</html>

**Comment by JingyaHuang** [comment]
@lewisbails I will merge this PR, pls feel free to open an issue so that we can continue our discussion on improving the performance of Big bird there.

**Comment by JingyaHuang** [comment]
FYI, some benchmark results for long sequences: https://medium.com/microsoftazure/faster-and-smaller-quantized-nlp-with-hugging-face-and-onnx-runtime-ec5525473bb7

**Comment by lewisbails** [comment]
Thanks for the link @JingyaHuang. I don't see a section for model performance with long sequence length in that blog post. They seem to say they test sequences between 4 and 512 tokens, but not much else. I can open an issue for this so we can continue the discussion there.

**Pull request merged**
