### PR TITLE
Fix benchmark tests

### PR DESCRIPTION
**Pull request by fxmarty**
This PR improves the benchmark tests in several ways:
* Use temporary files/folders
* Do not clone optimum main, use the current version (useful in PRs)
* Use tiny models (<10 MB)
* Refactor in a single file
* Remove tests on MacOS taking time 
 
Note that the tests will NOT pass until https://github.com/huggingface/optimum/pull/197 is merged. This is because we use `hf-internal-testing/tiny-bert-for-token-classification` that has a different label mapping than conll2003.

cc @philschmid

### CODE REVIEW

**Comment by philschmid** [comment]
@fxmarty what is the state here? When can we get those in?

**Comment by fxmarty** [comment]
Hi @philschmid , feel free to merge https://github.com/huggingface/optimum/pull/197 (I have no merge rights), I can then rebase this PR and it can be merged. One week ago when I did it, I made sure that tests pass given https://github.com/huggingface/optimum/pull/197 is merged.

**Comment by philschmid** [comment]
> Hi @philschmid , feel free to merge https://github.com/huggingface/optimum/pull/197 (I have no merge rights), I can then rebase this PR and it can be merged. One week ago when I did it, I made sure that tests pass given https://github.com/huggingface/optimum/pull/197 is merged.

Ah i didn't know that you cannot merge! 

What about the failing tests?

**Comment by fxmarty** [comment]
One test fails because it uses a tiny model (`hf-internal-testing/tiny-bert-for-token-classification`) that has a different label mapping than conll2003, so the optimum example script gives very low performance results. That's why I was thinking merging https://github.com/huggingface/optimum/pull/197 first, otherwise I can do a PR on the model to fix the label mapping, or use an other (larger) model for the test.

**Pull request merged**
