### PR TITLE
Fix build PR doc workflow

### PR DESCRIPTION
**Pull request by fxmarty**
The Furiosa docbuilding requires secrets.

PRs from forks need to be labeled `build-pr-doc` to run the workflow.

### CODE REVIEW

**Comment by fxmarty** [comment]
@regisss I don't get why the build PR doc workflow is not picked now. Any idea?

**Comment by regisss** [comment]
> @regisss I don't get why the build PR doc workflow is not picked now on this PR. I don't expect we need to merge first for it to be triggered. Any idea?
> 
> edit: let's just try to merge

I think this is because of
```
 paths:
      - "optimum/**.py"
      - "docs/**.mdx"
      - "docs/**.yml"
```
Since you just modified GH workflows but nothing in `optimum/` or `docs/`, the PR doc build workflow was not triggered.

**Comment by fxmarty** [comment]
I did in https://github.com/huggingface/optimum/pull/1270/commits/7a4a333863d46129d5ea51155a0a63f99cb5c6ba

**Comment by fxmarty** [comment]
Not sure why but looks to work now.

**Pull request merged**
