### PR TITLE
Add support for CPU Inference

### PR DESCRIPTION
**Pull request by vivekkhandelwal1**
Refer: https://github.com/PanQiWei/AutoGPTQ/pull/385

Signed-Off By: Vivek Khandelwal <vivek@nod-labs.com>

### CODE REVIEW

**Comment by vivekkhandelwal1** [comment]
@fxmarty @SunMarc can you please review this PR?

**Review by fxmarty — APPROVED** [review]
LGTM

**Comment by fxmarty** [comment]
Can you change the requirements to put AutoGPTQ>=0.5.0?

**Comment by vivekkhandelwal1** [comment]
> Can you change the requirements to put AutoGPTQ>=0.5.0?

The transformer's requirements?

**Comment by fxmarty** [comment]
Nevermind. There's actually no `auto-gptq` in setup.py. You can change `AUTOGPTQ_MINIMUM_VERSION` in `utils/import_utils.py`

**Comment by vivekkhandelwal1** [comment]
@fxmarty I have updated the PR with the required changes.

**Review by fxmarty — APPROVED** [review]
LGTM! I will merge it once the corresponding PR in AutoGPTQ is merged :)

**Pull request merged**
