### PR TITLE
Fix initializer detection for weight deduplication

### PR DESCRIPTION
**Pull request by fxmarty**
As per title. It is unclear why the CI is green (https://github.com/huggingface/optimum/actions/runs/6050752962/job/16420709454) although there was still this bug cc @xenova

### CODE REVIEW

**Comment by xenova** [comment]
After running a few more tests, decoder-only models seem to work quite well! 👍  massive reductions in size.

One I did run into a problem for was `nlpconnect/vit-gpt2-image-captioning`, which is an encoder-decoder architecture (encoder=vit, decoder=gpt2). There shouldn't be any weights shared between the two (unlike text2text models), so this should be possible.

```
Post-processing the exported models...
Deduplicating shared (tied) weights...
Could not find ONNX initializer for torch parameter decoder.lm_head.weight. decoder.lm_head.weight will not be checked for deduplication.
Found different candidate ONNX initializers (likely duplicate) for the tied weights:
	decoder.lm_head.weight: set()
	decoder.transformer.wte.weight: {'decoder.transformer.wte.weight'}
Could not find unique initializers corresponding to the torch tied parameters ['decoder.lm_head.weight', 'decoder.transformer.wte.weight']. Deduplication will be skipped for this group of weights although it should be done. Please open an issue in Optimum repository.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/optimum/exporters/onnx/__main__.py", line 503, in main_export
    models_and_onnx_configs, onnx_files_subpaths = onnx_config.post_process_exported_models(
  File "/usr/local/lib/python3.10/dist-packages/optimum/exporters/onnx/config.py", line 396, in post_process_exported_models
    models_and_onnx_configs, onnx_files_subpaths = super().post_process_exported_models(
  File "/usr/local/lib/python3.10/dist-packages/optimum/exporters/onnx/base.py", line 949, in post_process_exported_models
    models_and_onnx_configs, onnx_files_subpaths = super().post_process_exported_models(
  File "/usr/local/lib/python3.10/dist-packages/optimum/exporters/onnx/base.py", line 531, in post_process_exported_models
    remove_duplicate_weights_from_tied_info(
  File "/usr/local/lib/python3.10/dist-packages/optimum/onnx/graph_transformations.py", line 94, in remove_duplicate_weights_from_tied_info
    onnx_model = _deduplicate_gather_matmul(onnx_model, tied_groups_to_tie, tied_groups_map, initializer_name_to_idx)
  File "/usr/local/lib/python3.10/dist-packages/optimum/onnx/transformations_utils.py", line 458, in _deduplicate_gather_matmul
    torch_to_initializer = tied_groups_map[tuple(params)]
KeyError: ('decoder.lm_head.weight', 'decoder.transformer.wte.weight')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/content/transformers.js/scripts/convert.py", line 328, in <module>
    main()
  File "/content/transformers.js/scripts/convert.py", line 289, in main
    main_export(**export_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/optimum/exporters/onnx/__main__.py", line 507, in main_export
    raise Exception(
Exception: The post-processing of the ONNX export failed. The export can still be performed by passing the option --no-post-process. Detailed error: ('decoder.lm_head.weight', 'decoder.transformer.wte.weight')
```

**Comment by xenova** [comment]
More testing: https://huggingface.co/Xenova/tiny_starcoder_py/tree/main/onnx is producing very different model sizes for merged and unmerged models (68MB difference):
image

another problem is that the [original model ](https://huggingface.co/bigcode/tiny_starcoder_py) is 164M params, so I would expect the quantized model to be nearer to 164 MB

**Comment by fxmarty** [comment]
> One I did run into a problem for was nlpconnect/vit-gpt2-image-captioning, which is an encoder-decoder architecture (encoder=vit, decoder=gpt2). There shouldn't be any weights shared between the two (unlike text2text models), so this should be possible.

I am not sure to understand what you mean. Accelerate's [find_tied_parameters](https://github.com/huggingface/accelerate/blob/739b135f8367becb67ffaada12fe76e3aa60fefd/src/accelerate/utils/modeling.py#L464) do find `[decoder.lm_head.weight', 'decoder.transformer.wte.weight']` that are shared for gpt2. And inspecting the exported model from `optimum-cli export onnx --model nlpconnect/vit-gpt2-image-captioning vit_gpt2` with netron, this weight is indeed shared (and I don't run into the error you have).

Are you sure you checked out on the correct branch?

**Comment by fxmarty** [comment]
> More testing: https://huggingface.co/Xenova/tiny_starcoder_py/tree/main/onnx is producing very different model sizes for merged and unmerged models (68MB difference):

This is a different issue I believe. Basically the `Constant` nodes are not deduplicated in the merged decoder since we only deduplicate initializers. For this specific model, it appears that a `Slice` operator takes an input `data` as a Constant and not as an Initializer, hence the silent non-duplication.

**Comment by fxmarty** [comment]
@xenova The issue for encoder decoders should be fixed, could you give it a try?

Actually the CI was green because we never error out on deduplication failure. Maybe we should.

**Comment by xenova** [comment]
Will do testing now!

**Comment by xenova** [comment]
Can confirm this fixes all the above issues! (bart, vision-encoder, decoder, m2m_100 and many more...)
For example, [Xenova/nllb-200-distilled-600M](https://huggingface.co/Xenova/nllb-200-distilled-600M/tree/main/onnx)'s decoder went from 2.91GB -> 1.86GB! 🤯

**Comment by xenova** [comment]
Just tested t5-small, and I get the following error:
```
Post-processing the exported models...
Deduplicating shared (tied) weights...
Could not find ONNX initializer for torch parameter decoder.embed_tokens.weight. decoder.embed_tokens.weight will not be checked for deduplication.
Could not find ONNX initializer for torch parameter encoder.embed_tokens.weight. encoder.embed_tokens.weight will not be checked for deduplication.
Found different candidate ONNX initializers (likely duplicate) for the tied weights:
	decoder.embed_tokens.weight: set() --> ignored (may be a parameter from a part of the model not exported)
	encoder.embed_tokens.weight: set() --> ignored (may be a parameter from a part of the model not exported)
	lm_head.weight: {'onnx::MatMul_1430'}
	shared.weight: {'shared.weight'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/optimum/exporters/onnx/__main__.py", line 503, in main_export
    models_and_onnx_configs, onnx_files_subpaths = onnx_config.post_process_exported_models(
  File "/usr/local/lib/python3.10/dist-packages/optimum/exporters/onnx/base.py", line 949, in post_process_exported_models
    models_and_onnx_configs, onnx_files_subpaths = super().post_process_exported_models(
  File "/usr/local/lib/python3.10/dist-packages/optimum/exporters/onnx/base.py", line 531, in post_process_exported_models
    remove_duplicate_weights_from_tied_info(
  File "/usr/local/lib/python3.10/dist-packages/optimum/onnx/graph_transformations.py", line 99, in remove_duplicate_weights_from_tied_info
    onnx_model = _deduplicate_gather_matmul(onnx_model, tied_groups_to_tie, tied_groups_map, initializer_name_to_idx)
  File "/usr/local/lib/python3.10/dist-packages/optimum/onnx/transformations_utils.py", line 506, in _deduplicate_gather_matmul
    initializer_name = next(iter(torch_to_initializer[i]["initializer_name"]))
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/content/transformers.js/scripts/convert.py", line 351, in <module>
    main()
  File "/content/transformers.js/scripts/convert.py", line 312, in main
    main_export(**export_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/optimum/exporters/onnx/__main__.py", line 507, in main_export
    raise Exception(
Exception: The post-processing of the ONNX export failed. The export can still be performed by passing the option --no-post-process. Detailed error: 
```

**Comment by fxmarty** [comment]
> Just one thing to check: when converting a >2GB file to ONNX, and then doing the weight deduplication, then the model is <2GB, the original file remains. (https://huggingface.co/Xenova/nllb-200-distilled-600M/tree/main/onnx). Is this intended?

Wow good catch. This is not intended!

**Comment by xenova** [comment]
I can confirm that t5-small now works! The decoder goes from 233MB &rarr; 167MB (-28%)

**Comment by fxmarty** [comment]
@xenova https://github.com/huggingface/optimum/pull/1333#issuecomment-1705407400 should be fixed, and this PR good to go!

**Comment by fxmarty** [comment]
@echarlaix suggested to use `do_constant_folding=False`, and use ONNX Runtime optimizer to then remove the duplicated initializers. We may change to that later.

**Review by xenova — APPROVED** [review]
Converted the rest of the [opus-mt](https://huggingface.co/models?library=transformers.js&other=marian&sort=trending) models and everything seems to work well! 🚢

**Pull request merged**
