### PR TITLE
Add ONNX support for RegNet

### LINKED ISSUE #555: Community contribution -  `optimum.exporters.onnx` support for new models!
Following what was done by @ChainYo in Transformers, in the [ONNXConfig: Add a configuration for all available models](https://github.com/huggingface/transformers/issues/16308) issue, the idea is to add support for exporting new models in `optimum.exporters.onnx`.

This issue is about the working group specially created for this task. If you are interested in helping out, reply here, take a look at this [organization](https://huggingface.co/OWG), or add  `ChainYo#3610` on discord.

We want to contribute to Hugging Face's ONNX export implementation for all available models on Hugging Face Hub. There are already a lot of architectures implemented for converting PyTorch models to ONNX, but we need more! We need them all!

Feel free to join us in this adventure! Join the org by clicking [here](https://huggingface.co/organizations/OWG/share/TskjfGaGjGnMXXssbPPXrQWEIbosGqZshZ)

Here is a non-exhaustive list of models that all models available:

- [x] Albert
- [x] BART
- [x] BeiT
- [x] BERT
- [ ] BigBird (Critical issue: https://github.com/huggingface/optimum/issues/754#issuecomment-1429830467)
- [ ] BigBirdPegasus (Critical issue: https://github.com/huggingface/optimum/issues/754#issuecomment-1429830467)
- [x] Blenderbot
- [x] BlenderbotSmall
- [ ] BLIP-2
- [x] BLOOM
- [x] CamemBERT
- [ ] CANINE
- [x] CLIP
- [x] CodeGen
- [x] ConvNext
- [x] ConvBert
- [ ] CTRL
- [x] CvT
- [x] Data2VecText
- [x] Data2VecVision
- [x] Deberta
- [x] DebertaV2
- [x] DeiT
- [ ] DecisionTransformer
- [x] DETR
- [x] Distilbert
- [ ] DPR
- [x] DPT
- [x] ELECTRA
- [ ] FNet
- [ ] FSMT
- [x] Flaubert
- [ ] FLAVA
- [ ] Funnel Transformer
- [x] GLPN
- [x] GPT2
- [x] GPTJ
- [x] GPT-Neo
- [x] GPT-NeoX
- [x] Hubert
- [x] I-Bert
- [x] ImageGPT 🛠️ @adit299 
- [ ] LED
- [x] LayoutLM
- [ ] LayoutLMv2 (but 🛠️ in Transformers)
- [x] LayoutLMv3
- [ ] LayoutXLM
- [ ] LED
- [x] LeViT
- [ ] 🛠️ Longformer (Critical issue: https://github.com/huggingface/optimum/issues/776#issuecomment-1429680121)
- [x] LongT5
- [ ] Luke (but 🛠️ in Transformers)
- [ ] Lxmert
- [x] M2M100
- [ ] MaskFormer
- [x] mBart
- [ ] MCTCT
- [x] MPNet
- [x] MT5
- [x] MarianMT
- [ ] MegatronBert
- [x] MobileBert
- [x] MobileViT
- [ ] Nyströmformer
- [x] OpenAIGPT-2
- [x] OPT ((but 🛠️ in Transformers)
- [x] OWLViT
- [x] Pix2Struct
- [x] PLBart
- [x] Pegasus
- [x] Perceiver
- [x] PoolFormer
- [ ] ProphetNet
- [ ] QDQBERT
- [ ] RAG
- [ ] REALM
- [ ] Reformer (but 🛠️ in Transformers)
- [x] RemBert
- [x] ResNet
- [x] RegNet 🛠️ @asrimanth 
- [ ] RetriBert
- [x] RoFormer
- [x] RoBERTa
- [x] SEW
- [x] SEW-D
- [x] SegFormer
- [x] Speech2Text
- [ ] Speech2Text2
- [x] Splinter
- [x] SqueezeBERT
- [x] Swin Transformer
- [x] T5
- [ ] TAPAS 🛠️ @someshfengde 
- [ ] TAPEX
- [ ] Transformer XL
- [x] TrOCR
- [ ] UniSpeech
- [ ] UniSpeech-SAT
- [ ] VAN
- [x] ViT
- [ ] Vilt
- [ ] VisualBERT
- [x] Wav2Vec2
- [x] WavLM
- [x] Whisper
- [ ] XGLM
- [x] XLM
- [ ] XLMProphetNet
- [x] XLM-RoBERTa
- [x] XLM-RoBERTa-XL
- [ ]  XLNet (but 🛠️ in Transformers)
- [x] YOLOS
- [ ] Yoso

🛠️ next to a model suggests that the PR is in progress. If there is nothing next to a model, it means that ONNX does not yet support the model, and thus we need to add support for it.

If you need help implementing an unsupported model, here is a [guide](https://huggingface.co/docs/optimum/main/en/exporters/onnx/usage_guides/contribute) from HuggingFace Optimum documentation.

### PR DESCRIPTION
**Pull request by asrimanth**
Fixes #555

I've made the changes, however, is there any way I can verify whether my approach is correct? In other words, could anyone give me a few pointers as to how to test the integration locally?

- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by fxmarty** [comment]
Thank you @asrimanth ! You can try:

```
pip install -e .[tests,exporters]
pytest tests/exporters/onnx/test_*.py -k "regnet" -s
```

For slow tests:
```
pip install -e .[tests,exporters]
RUN_SLOW=1 pytest tests/exporters/onnx/test_*.py -k "regnet" -s -m "run_slow"
```

**Comment by asrimanth** [comment]
@fxmarty The test environment works locally now, thank you!

In the exporter_utils.py file, I wrote this earlier:

```
"regnet": "hf-internal-testing/tiny-random-RegNet"
```

However, this page (https://huggingface.co/hf-internal-testing/tiny-random-RegNet) does not exist. So I changed it to 

```
"regnet": "facebook/regnet-y-040",
```

Even though the URL exists (https://huggingface.co/facebook/regnet-y-040), I keep running into errors when I test locally. Please advise.

**Comment by fxmarty** [comment]
Hi @asrimanth you can maybe try https://huggingface.co/hf-internal-testing/tiny-random-RegNetModel

What errors are you running into?

**Comment by asrimanth** [comment]
Hello @fxmarty, Here's the error I'm getting:

```
=============================================================================== short test summary info ================================================================================
FAILED tests/exporters/onnx/test_exporters_onnx_cli.py::OnnxCLIExportTestCase::test_exporters_cli_pytorch_289_regnet_default - subprocess.CalledProcessError: Command 'python3 -m optimum.exporters.onnx --model hf-internal-testing/tiny-random-RegNetModel  --task default /var/folders/m4/tk3w_g0119d3bxf4s_zrn...
FAILED tests/exporters/onnx/test_exporters_onnx_cli.py::OnnxCLIExportTestCase::test_exporters_cli_pytorch_290_regnet_image_classification - subprocess.CalledProcessError: Command 'python3 -m optimum.exporters.onnx --model hf-internal-testing/tiny-random-RegNetModel  --task image-classification /var/folders/m4/tk3w_g01...
FAILED tests/exporters/onnx/test_exporters_onnx_cli.py::OnnxCLIExportTestCase::test_exporters_cli_pytorch_291_regnet_no_task - subprocess.CalledProcessError: Command 'python3 -m optimum.exporters.onnx --model hf-internal-testing/tiny-random-RegNetModel  /var/folders/m4/tk3w_g0119d3bxf4s_zrnsjr0000gn/T/tmp...
```

I think these are the errors caused by the line in the exporter_utils.py file. I've made the changes as follows:

```
"regnet": "hf-internal-testing/tiny-random-RegNetModel",
```

Since I'm new to open source, I'm open to advice.

**Comment by regisss** [comment]
Hi @asrimanth! Can you show us the detailed errors that are printed before this summary please? Unfortunately this test summary info cut the error messages so it is hard to know how to solve it.

**Comment by asrimanth** [comment]
Hello @regisss, thank you for your comment! 

You can see the full log in this commit here: https://github.com/huggingface/optimum/pull/833/commits/510845f8cd5622db4e6222d7165d49efbfd86ad1

If not, I've attached the local output as follows:
[log.txt](https://github.com/huggingface/optimum/files/10884425/log.txt)

**Comment by fxmarty** [comment]
@asrimanth Yes the last error in the trace is not informative unfortunately.

To see the full trace and where the issue comes from, you can try:

```
pytest tests/exporters/onnx/test_exporters_onnx_cli.py -k "test_exporters_cli_pytorch_290_regnet_image_classification" -s --full-trace
```

**Comment by asrimanth** [comment]
I've tried ```facebook/regnet-y-040``` and ```hf-internal-testing/tiny-random-RegNetModel``` using the full trace. Both of them show output as follows:

[log.txt](https://github.com/huggingface/optimum/files/10884648/log.txt)

As for the command: ```optimum-cli export onnx --model facebook/regnet-y-040 regnet_onnx/```, it throws the following error:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/Users/srimanth/Documents/TakeHome/optimum/optimum/exporters/__init__.py", line 15, in <module>
    from . import onnx  # noqa
  File "/Users/srimanth/Documents/TakeHome/optimum/optimum/exporters/onnx/__init__.py", line 16, in <module>
    from .base import OnnxConfig, OnnxConfigWithLoss, OnnxConfigWithPast, OnnxSeq2SeqConfigWithPast  # noqa
  File "/Users/srimanth/Documents/TakeHome/optimum/optimum/exporters/onnx/base.py", line 29, in <module>
    import onnx
ModuleNotFoundError: No module named 'onnx'
Traceback (most recent call last):
  File "/opt/homebrew/bin/optimum-cli", line 8, in <module>
    sys.exit(main())
  File "/Users/srimanth/Documents/TakeHome/optimum/optimum/commands/optimum_cli.py", line 40, in main
    service.run()
  File "/Users/srimanth/Documents/TakeHome/optimum/optimum/commands/export/onnx.py", line 173, in run
    subprocess.run(full_command, shell=True, check=True)
  File "/opt/homebrew/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'python3 -m optimum.exporters.onnx --model facebook/regnet-y-040 regnet_onnx/' returned non-zero exit status 1.
```

**Comment by regisss** [comment]
The package `onnx` is not installed in your environment it seems. Could you make sure you installed Optimum with the following command please?
```
pip install -e .[tests,exporters]
```

**Comment by asrimanth** [comment]
Hello @regisss, I've tried that on my local M1 Macbook air and it doesn't work. So I tried it on a different linux machine and all of the tests pass with 1 warning. You can see the output below:

```
> pytest tests/exporters/onnx/test_*.py -k "regnet" -s
============================================================================== test session starts ==============================================================================
platform linux -- Python 3.10.5, pytest-7.2.1, pluggy-1.0.0
rootdir: /nfs/nfs2/home/sragas/optimum, configfile: pyproject.toml
plugins: xdist-3.2.0, anyio-3.5.0
collected 1143 items / 1143 deselected / 0 selected                                                                                                                             

=============================================================================== warnings summary ================================================================================
<frozen importlib._bootstrap>:283
  <frozen importlib._bootstrap>:283: DeprecationWarning: the load_module() method is deprecated and slated for removal in Python 3.12; use exec_module() instead

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
====================================================================== 1143 deselected, 1 warning in 5.77s ======================================================================
```

**Comment by fxmarty** [comment]
Hi @asrimanth the tests indeed pass! There remains a conflict in `docs/source/exporters/onnx/package_reference/configuration.mdx`, could you solve it?

For that, you would need to pull on main, and merge or rebase into your branch, solving the conflict. It's probably just due to the fact that I moved the list of supported models in the doc to the overview page.

**Comment by fxmarty** [comment]
Thank you! You can add it here: https://github.com/huggingface/optimum/blob/main/docs/source/exporters/onnx/overview.mdx

**Comment by asrimanth** [comment]
I've made the documentation changes. Thank you @fxmarty, @regisss for helping me with my first open-source contribution!

**Comment by asrimanth** [comment]
@fxmarty, @regisss, The build failed in macOS. Any ideas on how to debug this?

**Review by fxmarty — APPROVED** [review]
The failing test is unrelated. Thank you for the addition!

**Comment by sushmanthreddy** [comment]
@asrimanth can u tell me , how to find supported_task_maping for a model?i have been trying to understand but I am quite confused.. pls tell me how to find supported_task_maping for a model??

**Comment by fxmarty** [comment]
Hi @sushmanthreddy , you can use this method: https://huggingface.co/docs/optimum/main/en/exporters/task_manager#optimum.exporters.TasksManager.get_supported_tasks_for_model_type

```python
from optimum.exporters import TasksManager

print(TasksManager.get_supported_tasks_for_model_type("bert", exporter="onnx").keys())
```

Are you asking in order to add a new architecture?

**Comment by sushmanthreddy** [comment]
@fxmarty yes I was asking for adding new architecture
BLIP-2 MODEL

**Comment by fxmarty** [comment]
Awesome, you could add it in the mapping here: https://github.com/huggingface/optimum/blob/d024c5f6f02e0aeb3f1d66505d60a122aa5a4a5f/optimum/exporters/tasks.py#L343

**Pull request merged**
