### PR TITLE
Add documentation for Optimum Furiosa

### PR DESCRIPTION
**Pull request by regisss**
# What does this PR do?

As per title.

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by regisss** [comment]
Doc build failing, need to find a way to install `furiosa-libnux`

**Comment by mht-sharma** [comment]
the reference and how-to-guide sections are also showing `FuriosaAI`. Any idea?

image

**Comment by regisss** [comment]
> the reference and how-to-guide sections are also showing `FuriosaAI`. Any idea?
> 
> image

Yeah there was a bug that I just fixed.
I'm also reverting to "FURIOSA" in the side bar as "FURIOSAAI" looks a bit ugly IMO.

**Comment by regisss** [comment]
@mht-sharma It should be better now. LEt me know if it's okay to merge!

**Review by mht-sharma — APPROVED** [review]
LGTM! Thanks @regisss

**Pull request merged**
