### PR TITLE
Bt bloom

### LINKED ISSUE #1175: BetterTransformer support for BLOOM
### Feature request

Can you please consider adding BetterTransformer support for BLOOM?

Thanks

### Motivation

Definitely this support will be of great help for people working with BLOOM.

### Your contribution

model = AutoModelForCausalLM.from_pretrained(hugg_path)      
model = BetterTransformer.transform(model)

### PR DESCRIPTION
**Pull request by baskrahmer**
# What does this PR do?

What the title says :)
In order to make the tests with key-value cache work, the input format had to be changed in order to be compatible with the Bloom cache format. Perhaps this could be automated by adding to Transformers directly (for the generate method this is done in https://github.com/huggingface/transformers/pull/20213)

Fixes #1175

Duplicate PR of #1187 but I messed up a bit with rebasing there, so I closed that one ;)

## Before submitting
- [x] Did you make sure to update the documentation with your changes?
- [x] Did you write any new necessary tests?

### CODE REVIEW

**Comment by nlpcat** [comment]
can i ask when we can get this PR merged to optimize bloom? pytorch just added attention bias memory efficient optimization. https://github.com/pytorch/pytorch/pull/104310

**Comment by nlpcat** [comment]
+ @fxmarty ?

**Comment by fxmarty** [comment]
Thank you, I'll make sure it is merged this week!

**Review by fxmarty — APPROVED** [review]
LGTM, thanks a lot for the addition @baskrahmer it is working smoothly!

About the `untangle batch_size from self.num_heads`, was it necessary for numerical equivalence?

**Pull request merged**
