### PR TITLE
update the default block size

### PR DESCRIPTION
**Pull request by rui-ren**
# What does this PR do?

Set the default `block_size = model_max_length`.

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Review by JingyaHuang — APPROVED** [review]
LGTM, thanks for contributing.

**Comment by rui-ren** [comment]
@JingyaHuang Hi, in [Transformer PyTorch Example ](https://github.com/rui-ren/transformers/blob/c817bc44e2915593a292df9e7d4e2c0dfefb6620/examples/pytorch/language-modeling/run_clm.py#L474-L480) ,  The block_size is default to `1027 if block_size > 1024:`. Do we need to update it accordingly? Otherwise the benchmarking for PyTorch vs Onnxruntime might be different cases. Thanks.

**Comment by rui-ren** [comment]
FYI, @JingyaHuang  https://github.com/huggingface/transformers/pull/24583

**Comment by JingyaHuang** [comment]
Hi @rui-ren, just to confirm the reason that you would not limit the block size, would it boost the performance of ORT, is the change ORT specific?

**Comment by JingyaHuang** [comment]
Yeah, so we suggest to keep the example aligned with what's in transformers unless the change benefits ORT's performance.

**Comment by rui-ren** [comment]
@JingyaHuang, 

I used this `run_clm.py` to run benchmark tests for models that `block_size` is larger than 2k, if we use the default of `block_size=1024`, and we might fail to test memory usage from the model itself.  That's the reason for this this PR.

However, it makes sense that I can add `--block-size xxx` to override the default 1024. I will revert this PR.

Thanks!

**Comment by rui-ren** [comment]
@JingyaHuang please check here https://github.com/huggingface/optimum/pull/1162 Thanks!

**Pull request merged**
