### PR TITLE
Add BetterTransformer support for RemBERT

### PR DESCRIPTION
**Pull request by hchings**
# What does this PR do?
Add BetterTransformer support for RemBERT (part of [#20372](https://github.com/huggingface/transformers/issues/20372))

## Before submitting
- ~~[ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case)~~.
- [x] Did you make sure to update the documentation with your changes?
- [x] Did you write any new necessary tests?

## Details 
- RemBERT's primary change is decoupling in/output embeddings. Since RemBERT uses the same Attention mechanism in BERT, it can use the same `BertLayerBetterTransformer`. (please correct me if I'm wrong)
- Minor code cleanup to sort model names alphabetically as the convention in transformers repo.
- All tests for encoders passed on GPU
Screen Shot 2022-12-04 at 3 57 10 PM

cc @younesbelkada, @michaelbenayoun, @fxmarty. Thanks.

### CODE REVIEW

**Review by younesbelkada — APPROVED** [review]
Thanks so much for adding `BetterTransformer` support for `RemBERT` 🎉 
Very clean PR! Thanks also for taking care of the alphabetical order on the testing suite 
Looking forward to your next contributions 💪

**Review by michaelbenayoun — APPROVED** [review]

**Comment by younesbelkada** [comment]
Thanks for the heads-up! Just run the workflow and we'll merge once it's green

**Comment by hchings** [comment]
Hi @younesbelkada, there are two checks failed.

1/ `test_inference_speed` in `test_bettertransformer_encoded.py`: this test only runs on `bert-base-uncased` model and will pass on GPU but can occasionally fail on CPU. All BetterTransformer-related PRs will have this check failed. Should we open an Issue to look into this?  
```
 AssertionError: 0.05959849110001869 not less than 0.056976150400032566 : The converted model is slower than the original model.
```
I think it's either PyTorch's issue or sth has to be changed in `BertLayerBetterTransformer` because even on CPU BetterTransformer is supposed to be faster. Please advise, thanks. 


2/ ONNX - I saw this test has been failing on main branch. And this is completely irrelevant to the code changes in this PR -- can we ignore it for merging this PR?

**Comment by younesbelkada** [comment]
Hi @hchings 
Thanks for your message
For 2/ this is expected as some tests are flaky so don't worry about that
For 1/ this is a bit strange since it passes on `mac-os` and not on `ubuntu`. This test used to be flaky and fails sometime. Let me get back to you on this

**Comment by younesbelkada** [comment]
Ok the test was just flaky, let's merge!

**Pull request merged**
