### PR TITLE
Adapt BaseConfig for next transformers release

### PR DESCRIPTION
**Pull request by echarlaix**
In this PR we fix https://github.com/huggingface/optimum/issues/344 by adapting `BaseConfig` in preview of transformers release v4.22.0

### CODE REVIEW

**Review by philschmid — COMMENTED** [review]
@echarlaix do we also need to make changes to the `ORTModel` classes for the `from_pretrained` method?

**Comment by echarlaix** [comment]
@philschmid No as `ORTModel` does not use any function that will be impacted by the breaking changes introduced in transformers 4.22.0

**Review by JingyaHuang — APPROVED** [review]
LGTM! 
Maybe not for this PR, but in general for codes inspired by transformers, do you think we shall add a line of transformers version check?

**Comment by echarlaix** [comment]
Good catch @JingyaHuang, I will add it before merging

**Pull request merged**
