### PR TITLE
re-enable decoder sequence classification

### PR DESCRIPTION
**Pull request by dwyatte**
# What does this PR do?

Re-enables sequence classification for decoder-based models. This requires a user to pass in `--pad_token_id` which required a change to the tests

I also removed a default pad token override for GPT-2 which seemed like a bad idea (sets it to 0, which corresponds to `!`) -- let me know if this is problematic 

This passes a fair number of tests in `tests/exporters/onnx/` for me, but I deselected some so we may need to iterate here

Fixes https://github.com/huggingface/optimum/issues/1527

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Review by fxmarty — APPROVED** [review]
LGTM thank you for the fix!

**Comment by dwyatte** [comment]
Digging into some test failures

Failing on main:
FAILED onnxruntime/test_quantization.py::ORTDynamicQuantizationTest::test_dynamic_quantization_subgraphs - AttributeError: 'NoneType' object has no attribute 'HasField'

Failing on this branch:
```
FAILED exporters/onnx/test_exporters_onnx_cli.py::OnnxCLIExportTestCase::test_exporters_cli_pytorch_cpu_060_bloom_feature_extraction_with_past_default_hf_internal_testing_tiny_random_BloomModel - RuntimeError: dictionary changed size during iteration
FAILED exporters/onnx/test_exporters_onnx_cli.py::OnnxCLIExportTestCase::test_exporters_cli_pytorch_cpu_061_bloom_feature_extraction_with_past_no_postprocess_default_hf_internal_testing_tiny_random_BloomModel - RuntimeError: dictionary changed size during iteration
FAILED exporters/onnx/test_exporters_onnx_cli.py::OnnxCLIExportTestCase::test_exporters_cli_pytorch_cpu_no_dynamic_axes_07_gpt2_feature_extraction_with_past_default_hf_internal_testing_tiny_random_gpt2 - RuntimeError: dictionary changed size during iteration
FAILED exporters/onnx/test_exporters_onnx_cli.py::OnnxCLIExportTestCase::test_exporters_cli_pytorch_cpu_no_dynamic_axes_08_gpt2_feature_extraction_with_past_no_postprocess_default_hf_internal_testing_tiny_random_gpt2 - RuntimeError: dictionary changed size during iteration
```

These pass locally for me, but appear to print out some warnings 

```
========================================================================================================================================= warnings summary ==========================================================================================================================================
tests/exporters/onnx/test_exporters_onnx_cli.py::OnnxCLIExportTestCase::test_exporters_cli_pytorch_cpu_230_gpt2_feature_extraction_with_past_default_hf_internal_testing_tiny_random_gpt2
  /mnt/nfs/dwyatte/Development/cash-customer-support-ml/user-folders/dwyatte/optimum/venv/lib/python3.9/site-packages/torch/_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
    return self.fget.__get__(instance, owner)()

tests/exporters/onnx/test_exporters_onnx_cli.py::OnnxCLIExportTestCase::test_exporters_cli_pytorch_cpu_230_gpt2_feature_extraction_with_past_default_hf_internal_testing_tiny_random_gpt2
tests/exporters/onnx/test_exporters_onnx_cli.py::OnnxCLIExportTestCase::test_exporters_cli_pytorch_cpu_231_gpt2_feature_extraction_with_past_no_postprocess_default_hf_internal_testing_tiny_random_gpt2
tests/exporters/onnx/test_exporters_onnx_cli.py::OnnxCLIExportTestCase::test_exporters_cli_pytorch_cpu_no_dynamic_axes_07_gpt2_feature_extraction_with_past_default_hf_internal_testing_tiny_random_gpt2
tests/exporters/onnx/test_exporters_onnx_cli.py::OnnxCLIExportTestCase::test_exporters_cli_pytorch_cpu_no_dynamic_axes_08_gpt2_feature_extraction_with_past_no_postprocess_default_hf_internal_testing_tiny_random_gpt2
  /mnt/nfs/dwyatte/Development/cash-customer-support-ml/user-folders/dwyatte/optimum/venv/lib/python3.9/site-packages/transformers/models/gpt2/modeling_gpt2.py:801: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
    if batch_size <= 0:

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
====================================================================================================================== 614 passed, 2 skipped, 7 warnings in 163.98s (0:02:43) =======================================================================================================================
```

Results of `optimum-cli env`:

Copy-and-paste the text below in your GitHub issue:

- `optimum` version: 1.17.0.dev0
- `transformers` version: 4.37.2
- Platform: Linux-4.19.0-25-cloud-amd64-x86_64-with-glibc2.35
- Python version: 3.9.17
- Huggingface_hub version: 0.19.4
- PyTorch version (GPU?): 2.1.2+cu121 (cuda availabe: False)
- Tensorflow version (GPU?): not installed (cuda availabe: NA)

**Comment by fxmarty** [comment]
Thank you @dwyatte, these failing tests are fine as unrelated, and fixed in https://github.com/huggingface/optimum/pull/1683 & https://github.com/microsoft/onnxruntime/pull/19421

**Comment by dwyatte** [comment]
Great, just rebased so I think this should be ready to go now

**Comment by fxmarty** [comment]
Thank you!

**Pull request merged**
