### PR TITLE
Update doc homepage

### PR DESCRIPTION
**Pull request by regisss**
# What does this PR do?

Following the discussion in https://github.com/huggingface-internal/moon-landing/pull/10992. This PR modifies the doc homepage to better reflect our strategic partnerships (cloud, hardware and on-prem) as it is now the page where [huggingface.co/hardware](https://huggingface.co/hardware) redirects to.

In particular, it follows @jeffboudier's [idea](https://github.com/huggingface-internal/moon-landing/pull/10992#issuecomment-2338794749):
> Such a partners page in my mind would have a broader scope, e.g.
>   - cloud partners: amazon google azure cloudflare
>   - hardware partners: nvidia amd intel aws tpu furiosa
>   - on prem partners: dell

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by julien-c** [comment]
neat!

**Comment by regisss** [comment]
@jeffboudier @julien-c @philschmid @mfuntowicz @VioletteLepercq @pagezyhf @echarlaix Here is a first draft for revamping the homepage of the Optimum doc: https://moon-ci-docs.huggingface.co/docs/optimum/pr_2029/en/index

The goal is to make it the landing page for hardware and cloud partnerships. It's a first quick iteration so it's far from being perfect, let me know what you think and where it can be improved!

In particular, check the links each tile leads to. I didn't find a good HF-hosted resource for Azure, and for Dell it's a link to their entreprise hub.

**Comment by regisss** [comment]
@jeffboudier Not sure if hardware@huggingface.co is still active or if there is a better email address to give

**Comment by regisss** [comment]
Also, I deliberately chose to not add anything to the sidebar as it's already dense but happy to reconsider it if you think it makes sense

**Comment by VioletteLepercq** [comment]
nice!!

**Comment by pagezyhf** [comment]
Nice! Super cool to have a central place for partnerships.

I looked at the hyperlink of the Cloud partnerships and here's my suggestion:
- Azure: https://huggingface.co/blog/hugging-face-endpoints-on-azure
- GCP: LGTM
- Cloudflare: LGTM
- AWS: LGTM
- We could add a section for NVIDIA once they update their organization page (Autotrain on DGXCloud + NIM API (serverless)) ?

Optimum is certainly the best candidate as of now to host this central repository of partnerships. However, some cloud partnership don't relate to optimum so I would move the section down:
1. Hardware partners
2. Cloud partners
3. On-prem partners
4. Open Source integrations
Also, I would switch hardware and cloud partnership order.

**Comment by jeffboudier** [comment]
Thanks @regisss !

To clarify my previous comments in https://github.com/huggingface-internal/moon-landing/pull/10992 :
1. today, we can replace the destination of the Solutions > Hardware header menu, from current /hardware marketing page, to https://huggingface.co/docs/optimum/index, as the current /hardware marketing page is outdated and unmaintained
2. tomorrow, instead of updating the Hardware marketing page, it would make sense to create a new "Partners" marketing page, with a broader scope, and have that as a new Solutions > Partners site header navigation.

Today, Optimum packages focus on our hardware collaborations, so I'm not sure it makes sense for the home of its documentation to present our broader partnerships, some of which do not require Optimum for usage. If we wanted to use documentation in order to present all our broader partnerships, then the Hub docs may be a better fit - and even then I still think a simple marketing page for newcomers would help newcomers.

**Comment by julien-c** [comment]
>  If we wanted to use documentation in order to present all our broader partnerships

The advantage i see is that doc pages are simpler to keep in sync / maintain over time. But both options (doc page or marketing page) work

**Comment by regisss** [comment]
I agree with Julien that a doc page is easier to maintain but on the other hand I agree that some partnerships are a bit out of place in the homepage of the Optimum doc.
A single marketing page seems to be a better solution. I can start working on it next week, that way I'll know how to update it in the future to ensure we can maintain it pretty easily. Closing this one.

**Pull request closed without merging**
