### PR TITLE
fix: ValueError offload_dir

### PR DESCRIPTION
**Pull request by orangetin**
Fixes the following error when model as weights offloaded to disk by providing an optional `offload_dir` argument that can be used with `BetterTransformer.transform`:

 `ValueError: We need an 'offload_dir' to dispatch this model according to this 'device_map', the following submodules need to be offloaded...`

Example:

`model = BetterTransformer.transform(model_hf, keep_original_model=True, offload_dir="OFFLOAD-DIR")`

Let me know if you have any suggestions!

P.S. I don't think any of the below options applies
## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Review by fxmarty — COMMENTED** [review]
LGTM, waiting for @younesbelkada to check as he's more familiar with accelerate

**Review by fxmarty — APPROVED** [review]

**Comment by fxmarty** [comment]
Can you run `make style`?

**Comment by fxmarty** [comment]
Can you try `pip uninstall ruff && pip install -U -e .[quality] && make style`?

**Comment by orangetin** [comment]
Done

That worked, thanks!

**Comment by orangetin** [comment]
@younesbelkada @fxmarty can I get a review?

**Review by younesbelkada — COMMENTED** [review]
Thanks a lot for the PR! 
The changes looks really good! Could you resolve the conflicts before merging? I will merge right after that

**Comment by orangetin** [comment]
> Thanks a lot for the PR! The changes looks really good! Could you resolve the conflicts before merging? I will merge right after that

Resolved. Thanks!

**Comment by orangetin** [comment]
Fixed style

**Review by younesbelkada — APPROVED** [review]
Thanks a lot for fixing!

**Pull request merged**
