### PR TITLE
Remove version pinning for onnx package

### LINKED ISSUE #1140: Unpin onnx version to allow using v1.14
### Feature request

Remove the version constraint on onnx package to allow using onnx==1.14.

### Motivation

- The latest version of onnxruntime (v1.15 at the time of writing) supports onnx==1.14.
- onnx==1.14 introduces support for protobuf v4, which is also useful.

### Your contribution

Seems removing the pin from setup.py would be all that is needed as long as the existing tests provide enough validation.

### PR DESCRIPTION
**Pull request by cody-moveworks**
The latest version of onnxruntime package (v1.15.1 at the time of writing) supports onnx v1.14.0, so we do not need to pin onnx package version to be below v1.14.0 anymore.

# What does this PR do?

This PR removes the version pinning for onnx package. This will allow using the latest version of onnxruntime package. The v1.14.0 release of onnx package also introduces support for protobuf v4, which is nice bonus. 

Fixes #1140

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by cody-moveworks** [comment]
@regisss PTAL.

**Review by regisss — APPROVED** [review]
LGTM!
Let's see the results of the tests

**Comment by regisss** [comment]
@cody-moveworks Regarding Protobuf v4, Transformers currently has the following dependency: `"protobuf<=3.20.3"`.
So it won't be compatible with Optimum right away. An issue was recently opened there in case you're interested: https://github.com/huggingface/transformers/issues/24323

**Comment by regisss** [comment]
@cody-moveworks Protobuf v4 support has been merged in Transformers: https://github.com/huggingface/transformers/pull/24599
So this should be compatible with Optimum, you'll just have to install Transformers from source till a new version is released.

**Comment by cody-moveworks** [comment]
@regisss Thanks for letting me know! That's great to see :)

**Pull request merged**
