### PR TITLE
Fix bug where the PR doc is actually the main doc

### PR DESCRIPTION
**Pull request by regisss**
# What does this PR do?

In the Docker image associated to the container building the doc, the repo is cloned but it points by default to the main branch. Thus, the doc generated for each PR is actually the doc of the main branch. This is fixed by checking out the commit associated to the PR when cloning the repo in the Dockerfile. See [here](https://github.com/huggingface/optimum-habana/pull/78) for more explanations.

If the PR comes from a fork, it also clone the right repo in the Docker container. This must also be done for Optimum Graphcore/Habana/Intel.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Review by lewtun — APPROVED** [review]
Nice catch @regisss ! LGTM 🔥

**Comment by lewtun** [comment]
FYI just re-running the failed jobs (unrelated to this PR, but best to have a green CI)

**Comment by regisss** [comment]
> FYI just re-running the failed jobs (unrelated to this PR, but best to have a green CI)

@lewtun I fully agree with you and since this happens on all PRs I propose a "fix" in #352.

I'll merge this one once the tests are all supposed to pass.

**Comment by regisss** [comment]
All tests passed :partying_face:

**Pull request merged**
