### PR TITLE
Add MPT onnx and ORT support

### PR DESCRIPTION
**Pull request by jiqing-feng**
Hi @fxmarty @echarlaix 

Relate to [1101](https://github.com/huggingface/optimum/pull/1101). This PR enables MPT models onnx config to support generating dummy inputs.

The shape arrangement of `past_key_values` may be different across models. We can use the member variable `sequence_length` of `DummyPastKeyValuesGenerator` to identify the sequence length of `past_key_values`.

Would you please help me review it? Thanks

cc @changwangss

### CODE REVIEW

**Comment by fxmarty** [comment]
Hi @jiqing-feng , thank you for the PR! I'm personally not in favor of supporting custom models in Optimum that otherwise use `trust_remote_code=True`. I think it would make more sense to host custom ONNX configs in the model repos directly. What is your opinion @echarlaix @JingyaHuang @michaelbenayoun  ?

I propose https://github.com/huggingface/optimum/pull/1166 in this regard, see the API here: https://moon-ci-docs.huggingface.co/docs/optimum/pr_1166/en/exporters/onnx/usage_guides/export_a_model#custom-export-of-transformers-models

**Comment by jiqing-feng** [comment]
Hi @fxmarty . Thanks for your comment. 

The MPT model is going to upstream on transformers, see [24629](https://github.com/huggingface/transformers/pull/24629). We do not need `trust_remote_code=True` after the PR is merged. 

We can wait for the [24629](https://github.com/huggingface/transformers/pull/24629) merge and then we can discuss if we can move forward with my PR.

**Comment by JingyaHuang** [comment]
@fxmarty @jiqing-feng For the ease of maintenance,  Optimum shall only support configs of transformers native models. For those with`trust_remote_code`(chatglm and mpt for now), hosting directly on the hub sounds very nice to me. 

btw, mpt sounds like a good example to test a bit with what you suggest @fxmarty

**Comment by fxmarty** [comment]
Hi @jiqing-feng, for sure we can merge once there is a transformers release! Is the KV cache layout fine?

**Comment by jiqing-feng** [comment]
> Hi @jiqing-feng, for sure we can merge once there is a transformers release! Is the KV cache layout fine?

Yes! The KV cache layout is the same as most CLM models like llama. We can wait for the release.

**Comment by jiqing-feng** [comment]
Hi @fxmarty @JingyaHuang . I think we can move forward on this PR since the recently released version of transformers contained MPT model. I see that some checks have failed. Would you please tell me where and what kind of tests should I add?

**Comment by echarlaix** [comment]
> Would you please tell me where and what kind of tests should I add? Thx!

Could you add ONNX Runtime tests as well by adding the model name [here](https://github.com/huggingface/optimum/blob/v1.12.0/tests/onnxruntime/test_modeling.py#L1945) and [here](https://github.com/huggingface/optimum/blob/v1.12.0/tests/onnxruntime/utils_onnxruntime_tests.py#L28) using a tiny random model like this [one](hf-internal-testing/tiny-random-MptForCausalLM)?

**Comment by jiqing-feng** [comment]
> > Would you please tell me where and what kind of tests should I add? Thx!
> 
> Could you add ONNX Runtime tests as well by adding the model name [here](https://github.com/huggingface/optimum/blob/v1.12.0/tests/onnxruntime/test_modeling.py#L1945) and [here](https://github.com/huggingface/optimum/blob/v1.12.0/tests/onnxruntime/utils_onnxruntime_tests.py#L28) using a tiny random model like this [one](https://huggingface.co/hf-internal-testing/tiny-random-MptForCausalLM)?

Done. Thx!

**Comment by jiqing-feng** [comment]
Hi @echarlaix @fxmarty @JingyaHuang 

Could we merge this PR? I see that the failed checks are not related to my changes and the mpt model has been released in the latest released version of transformers. Thx!

**Pull request merged**
