### PR TITLE
Fix loading of an ONNX stable diffusion model when config doesn't match

### PR DESCRIPTION
**Pull request by echarlaix**
In this PR we enable the loading of stable diffusion ONNX model even when the model configuration is the model original configuration

### CODE REVIEW

**Review by sayakpaul — APPROVED** [review]
Thanks!

For more context, here's why this was needed. 

I exported [this ONNX Stable Diffusion model](https://huggingface.co/sayakpaul/onnx-stable-diffusion-v1-5) using the `optimum-cli`. But when I tried to load it using:

```py
from optimum.onnxruntime import ORTStableDiffusionPipeline

model_id = "sayakpaul/onnx-stable-diffusion-v1-5"
stable_diffusion = ORTStableDiffusionPipeline.from_pretrained(model_id)
```

it complained about:

```
NoSuchFile: [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from /root/.cache/huggingface/hub/models--sayakpaul--onnx-stable-diffusion-v1-5/snapshots/aa6a4470ad79a05673e6fd4a70104d146293d192/vae_decoder/model.onnx failed:Load model /root/.cache/huggingface/hub/models--sayakpaul--onnx-stable-diffusion-v1-5/snapshots/aa6a4470ad79a05673e6fd4a70104d146293d192/vae_decoder/model.onnx failed. File doesn't exist
```

**Comment by kopyl** [comment]
@echarlaix same error. How to fix it?

**Comment by kopyl** [comment]
I exported a model like this:

```
!optimum-cli export onnx --model sd-1_5-icons-172800_steps-4e_7 \
  --task stable-diffusion \
  --batch_size 1 \
  --height 512 \
  --width 512 \
  sd-1_5-icons-172800_steps-4e_7_onnx/
```

And it got me no model in a vae decoder.

**Comment by kopyl** [comment]
Exporting like this worked:
`onnx_pipeline = ORTStableDiffusionPipeline.from_pretrained(onnx_model_id, export=True)`

Why the previous method did not?

**Comment by echarlaix** [comment]
Hi @kopyl, 

I'm not able to reproduce your error, could it be that your device run out of memory during export ? Could you try again without specifying input shapes ? (more specifically the height/width)
```bash
optimum-cli export onnx --model model_id --task stable-diffusion output_dir/
```

**Comment by kopyl** [comment]
@echarlaix hey. It's no longer relevant, cause i already exported it like this:
```
onnx_pipeline = ORTStableDiffusionPipeline.from_pretrained(onnx_model_id, export=True)
onnx_pipeline.save_pretrained("onnx-mode
```

But thank you very much anyways.

Now just curious why is optimum model much slower than onnx export from this thing: https://nvidia.custhelp.com/app/answers/detail/a_id/5487/~/tensorrt-extension-for-stable-diffusion-web-ui

**Pull request merged**
