### PR TITLE
add normalizedconfig for baichuan and mixformer-sequential

### PR DESCRIPTION
**Pull request by changwangss**
# What does this PR do?

Fixes # (issue)
we want to use the models https://huggingface.co/baichuan-inc/Baichuan2-13B-Base and https://huggingface.co/microsoft/phi-1, but the normalizedconfig doesn't contain.

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you make sure to update the documentation with your changes?
- [x] Did you write any new necessary tests?

### CODE REVIEW

**Comment by michaelbenayoun** [comment]
I think the issu is that we can end-up with multiple names potentially pointing to different `NormalizedConfig`s. 

I think what we can do is allow the user to provide a `NormalizedConfig` on its own: 

1. When exporting the model via the `export` function it is trivial to do so
2. When exporting the model via the CLI, it is less trivial: either the desired `NormalizedConfig` already exists and in this case it can simply be the name of the `NormalizedConfig` to use, or it does not exist yet, in which case I think we can point the user to use the `export` function?

**Comment by fxmarty** [comment]
couldn't we just greedy and have a heuristic of most commonly used key names, and try to use those?

**Comment by michaelbenayoun** [comment]
Yes, we could do that.

**Review by PenghuiCheng — APPROVED** [review]

**Comment by changwangss** [comment]
> I think the issu is that we can end-up with multiple names potentially pointing to different `NormalizedConfig`s.
> 
> I think what we can do is allow the user to provide a `NormalizedConfig` on its own:
> 
> 1. When exporting the model via the `export` function it is trivial to do so
> 2. When exporting the model via the CLI, it is less trivial: either the desired `NormalizedConfig` already exists and in this case it can simply be the name of the `NormalizedConfig` to use, or it does not exist yet, in which case I think we can point the user to use the `export` function?

Could you have the plan continue to do this feature?  @fxmarty @michaelbenayoun 
I close the PR first and hope the feature can be completed soon

**Pull request closed without merging**
