### PR TITLE
Add benchmark results to gpu doc

### PR DESCRIPTION
**Pull request by JingyaHuang**
# What does this PR do?

Add benchmark results to GPU usage documentation.

### CODE REVIEW

**Comment by fxmarty** [comment]
It's really nice, thanks for adding this!

For me the figures are quite small, could we maybe put them one after the other? Or allow in JS to click and zoom (no idea if it's possible)? See:

image

Also, I'm not sure to understand the legend in the figures:

image

There are full and dotted black lines in the legend but not in the plot. Also dotted blue/orange lines, that are not in the legend. Is it expected?

**Comment by JingyaHuang** [comment]
@fxmarty ok, I will try to make the display better looking!

Nope, the legend is a combination of two groups of legends.

The first group is "Framework", which distinguishes PyTorch and ORT by color.
The second group is "Generation(mode)", which distinguishes greedy and beam search by solid and dashed lines.

**Comment by JingyaHuang** [comment]
@fxmarty Any better if I put legend this way?
Screenshot 2022-11-29 at 16 14 46

**Comment by fxmarty** [comment]
Yes it's much better, thanks a lot!

**Comment by JingyaHuang** [comment]
@fxmarty Graphs replaced!

**Review by fxmarty — APPROVED** [review]
LGTM, great job!

**Comment by regisss** [comment]
Awesome PR @JingyaHuang!!! :fire: :rocket:

**Pull request merged**
