### PR TITLE
added bettertransformerlayer for detr model

### PR DESCRIPTION
**Pull request by sushmanthreddy**
# What does this PR do?

This pull request is for the bettertransformermodel [#20372](https://github.com/huggingface/transformers/issues/20372)   and [#488](https://github.com/huggingface/optimum/issues/488) detr model. I have made the necessary changes pls review it and pls let me knew if any changes are needed 

@sgugger @amyeroberts  @younesbelkada  @michaelbenayoun   can anyone of u pls review it ??

### CODE REVIEW

**Comment by sushmanthreddy** [comment]
@younesbelkada is there any wrong iny code...? Is there any extra work should i do?

**Review by younesbelkada — COMMENTED** [review]
Hello @sushmanthreddy 
Thanks for your PR, can you run the styling checks? `make style && make quality`

**Comment by sushmanthreddy** [comment]
@younesbelkada i don't know how to run the styling checks , can u pls provide some documentation ,i could follow??

**Comment by sushmanthreddy** [comment]
I want to run local tests also in my local machine for better transformer model...but I dont know how to do pls...it would be helpful ,i fu provide some documentation

**Comment by regisss** [comment]
There is no `make quality` in Optimum actually XD

@sushmanthreddy Follow the steps 4 and 6 described here for formatting the code the right way: https://github.com/huggingface/optimum/blob/main/CONTRIBUTING.md#how-to-create-a-pull-request

**Comment by younesbelkada** [comment]
Yes I second what @regisss said !
To run the styling checks just run
```bash
make style
```
(and not make quality :D )
For the tests you can start over by just running `pytest tests/bettertransformer`

**Comment by sushmanthreddy** [comment]
@regisss  I think my code wasn't passing some of the checks ...can u pls just give some hint where i was going worng??

**Comment by regisss** [comment]
> @regisss @younesbelkada I think my code wasn't passing some of the checks ...can u pls just give some hint where I was going wrong??

I think many tests failed because you wrote DETR in upper case in the test files, while it shoud be in lower case: detr.

**Pull request closed without merging**
